/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.cc.solver.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EqNotEq = 10;
  /** RegularExpression Id. */
  int CADR = 13;
  /** RegularExpression Id. */
  int PRED = 14;
  /** RegularExpression Id. */
  int FUNVAR = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "<EqNotEq>",
    "\"atom\"",
    "\"cons\"",
    "<CADR>",
    "<PRED>",
    "<FUNVAR>",
  };

}
